const AGENTS_AMOUNT = 360;
const AGENT_MAIN_COLOR = '#ff0000';
const AGENT_SUPPORT_COLOR = '#b29f20';

const TARGETS_AMOUNT = 2;
const TARGETS_COLOR = '#9d00ff';
const MOUSE_TARGET_COLOR = '#ffffff';

const TARGET_SPEED_MODIFIER = 2;

const VELOCITY_CLAMP = 9;
const ACCELERATION_CLAMP = 0.6;
const CACHE_LOOPS = 10;
