const AGENTS_AMOUNT = 30;
const AGENT_SIZE = 5;
const AGENT_MAIN_COLOR = '#ff0000';
const AGENT_SUPPORT_COLOR = '#b29f20';

const AGENT_DELTA_VALUE = 0.15;

const TARGETS_AMOUNT = 2;
const TARGETS_SIZE = 20;
const TARGETS_COLOR = '#9d00ff';

const MOUSE_TARGET_SIZE = 10;
const MOUSE_TARGET_COLOR = '#ffffff';

const TARGET_SPEED_MODIFIER = 2;

const VELOCITY_CLAMP = 7;
const ACCELERATION_CLAMP = 0.6;
